[build]
  command   = "npm install && npm run build"
  publish   = "dist"

[[redirects]]
  from     = "/admin/*"
  to       = "/admin/:splat"
  status   = 200

[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
